"""empty message

Revision ID: 3aeffe375474
Revises: 319089a7b20f
Create Date: 2023-07-23 17:11:03.694537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeffe375474'
down_revision = '319089a7b20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('desc_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('esrb', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('esrb')
        batch_op.drop_column('category')
        batch_op.drop_column('desc_image_url')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
